<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReviewCount($productId)
    {
        $queryBuilder = $this->createQueryBuilder('r');

        $query = $queryBuilder->select($queryBuilder->expr()->count('r'));

        return $query->getQuery()->getResult();
    }
}
