security:

    # ( Denchev ) - Access Denied (403) Page
    access_denied_url:

    #( Denchev ) - Where are Users loaded from
    providers:
        # ( Denchev ) - Users are loaded from a local database
        database_provider:
        # ( Denchev ) - No property as they'll be authenticated by either $username or $email
            entity:
                class: AppBundle\Entity\User

    # ( Denchev ) - User's password will be 'hashed' using bcrypt
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # ( Denchev ) - Main 'Firewall' Settings
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # ( Denchev ) - Matches anything
            pattern: ^/
            # ( Denchev ) - Anonymous browsing through pages is allowed
            anonymous: true

            #( Denchev ) - We'll be using the above specified User entity
            provider: database_provider

            # ( Denchev ) - Configuration for the login form
            form_login:
                #  ( Denchev ) - Login Path GET
                login_path: security_login
                # ( Denchev ) - Login Path POST
                check_path: security_login
                # ( Denchev ) - Redirect after login
                default_target_path: /
                # ( Denchev ) - CSRF Token generated by Symfony\Component\Security\Csrf\CsrfTokenManager
                csrf_token_generator: security.csrf.token_manager
                # csrf_token_id: custom_token_name

            #  ( Denchev ) - Configuration for logging out
            logout:
                #  ( Denchev ) - Logout URL
                path: /logout
                #  ( Denchev ) - Logout Redirects to
                target: /

    #  ( Denchev ) - Main Access Control Settings (ACL)
    access_control:
        #  ( Denchev ) - Routes accessible for everyone
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #  ( Denchev ) - At least logged in as basic user
        - { path: ^/.*/profile/edit, roles: ROLE_USER }
        - { path: ^/.*/profile/view, roles: ROLE_USER }
